OpenBankingToolkit/openbanking-reference-implementation

- .idea/runConfigurations/Openbanking_Config.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/src/main/java/com/forgerock/openbanking/analytics/ForgerockOpenbankingMetricsServicesApplication.java
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/src/main/java/com/forgerock/openbanking/monitoring/ForgerockOpenbankingMonitoringApplication.java
- forgerock-openbanking-config/forgerock-openbanking-git-config/jwkms/jwkms-native.yml
- forgerock-openbanking-config/forgerock-openbanking-git-config/jwkms/jwkms.yml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/src/main/java/com/forgerock/openbanking/register/ForgerockOpenbankingRegisterApplication.java
- pom.xml
> Use jcenter

- forgerock-openbanking-config/forgerock-openbanking-git-config/jwkms/jwkms.yml
> Makes it works with the basems

- .idea/runConfigurations/Openbanking_Config.xml
configuration profile config service changed composite to native to run correctly config service on local environment
> changed the profile composite to native

- .dependabot/config.yml
Enable dependabot without auto-merge to get a feeling of what will be
upgraded. We should enable auto-merge after.
* PRs for upgrading dependencies
> Add Dependabot to OB ref

- forgerock-openbanking-devportal/forgerock-openbanking-register/src/main/java/com/forgerock/openbanking/register/ForgerockOpenbankingRegisterApplication.java
- forgerock-openbanking-devportal/forgerock-openbanking-register/src/main/java/com/forgerock/openbanking/register/service/RegisterUserProvider.java
Register app refactored to use jwt cookie collector and JwtAuthentication from multi-auth library.
This fix the loggin issue:
https://github.com/ForgeCloud/ob-reference-implementation/issues/1856
> Issue 1856

- README.md
The README didn't have enough info on why specific actions were being taken.
> Improved section on setting up the JWKMS truststore

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
Move the mvn project to MADNESS
> Move mvn project release version to MADNESS

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
The analytics has been abstracted to offer a no op implementation by
default so SDK users aren't obliged to use the analytics
This change will enable it in the reference implementation
* all analytic services
Outline the steps to test or reproduce the PR here.
check analytics after running tests
> Add webclient analytics

- .idea/runConfigurations/as_api_remote.xml
- .idea/runConfigurations/directory_remote.xml
- .idea/runConfigurations/jwkms_remote.xml
- .idea/runConfigurations/monitoring_remote.xml
- .idea/runConfigurations/rs_api_remote.xml
- .idea/runConfigurations/rs_rcs_remote.xml
- .idea/runConfigurations/rs_store_remote.xml
- .idea/runConfigurations/rs_ui_remote.xml
- .idea/runConfigurations/scgw_remote.xml
- docker-compose.yml
Add remote debugging
* Docker compose
Outline the steps to test or reproduce the PR here.
1. docker-compose up -d
1. In intellij select remote rs-api
1. Run in debug mode
> Add remote debugging

- .idea/runConfigurations/as_api_remote.xml
- .idea/runConfigurations/directory_remote.xml
- .idea/runConfigurations/jwkms_remote.xml
- .idea/runConfigurations/monitoring_remote.xml
- .idea/runConfigurations/rs_api_remote.xml
- .idea/runConfigurations/rs_rcs_remote.xml
- .idea/runConfigurations/rs_store_remote.xml
- .idea/runConfigurations/rs_ui_remote.xml
- .idea/runConfigurations/scgw_remote.xml
- docker-compose.yml
Fix monitoring in docker-compose by adding am internal port.
Add all remote debug configuration
* docker-compose
* intellij
> Add monitoring fix

- pom.xml
Merged all changes from this morning's dependabot PRs into one. This will result in a much quicker deployment to master.
> Roll dependabot prs into one pr

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
> Perform Queen release

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/test/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/test/CSVFilePaymentConsentsRsApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/test/java/com/forgerock/openbanking/extensions/lbg/test/CSVFilePaymentConsentsRsStoreApiControllerIT.java
Implemented support for all rest versions.
From 3.0 to 3.1.2
* CSV files
> Support for all versions

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
- fixes https://github.com/OpenBankingToolkit/openbanking-reference-implementation/issues/150
> Create a 3.1.2-queen-rc3 release

- pom.xml
Update parent to last version
Update the parent maven descriptor to last version.
Dependencies
> Update parent to last version

- pom.xml
Update openbanking uk extensions to last version
Upgrade to the last version of openbanking extensions.
* aspsp - openbanking extensions
> Update openbanking uk extensions to last version

- codefresh.yml
Steps created on the pipeline to run the integration test for rs-api and rs-store
* aspsp-rs-api
* aspsp-rs-store
> Integration test enabled for rs-api and rs-store

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
Create 3.1.2-queen-rc4 maven release
> Set maven version to 3.1.2-queen-rc4

- codefresh.yml
Set the registry syntax explicitly in push type on the pipeline
> set the registry explicitly to push the images to cgr

- codefresh.yml
Reverts OpenBankingToolkit/openbanking-reference-implementation#213
> Revert "Tag images master branch"

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
Includes fixes for https://github.com/OpenBankingToolkit/openbanking-reference-implementation/pull/212
This PR increments versions of aspsp that include the fix for #212, and also includes newer versions of analytics and directory
> Bump versions ready to release 3.1.2-queen-rc6

- forgerock-openbanking-config/forgerock-openbanking-git-config/application-native.yml
- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
Enabled detached JWT signature verification within application.yml files.
> Waiver 007 expiry - enabled detached JWT signature verification (#219)

- pom.xml
This pulls in fixes that;
- improve rendering of forgerock theme in the UI
- Turns on detached jwt signing and validation of detached jwt
signatures
- Corrects bugs where some GET payment endpoints used token auth rather
than client credentials.
> Use v1.0.80 of openbanking-aspsp

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
Set project version ready for new iteration of queen
> Set project version to 3.1.2-queen-rc7

- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/src/main/java/com/forgerock/openbanking/analytics/ForgerockOpenbankingMetricsServicesApplication.java
To access the analytics we want use a specific privilege to restrict the access for the users that don't have that privilege configure on am directly.
The new feature enable add the authority GROUP_ANALYTICS on am associated with the user to access the analytics service.
Issue related:
#140
* Analytics
* metrics
> Privilege feature issue 140

- pom.xml
Bump latest versions to pull in fixes for
https://github.com/OpenBankingToolkit/openbanking-reference-implementation/issues/219
https://github.com/OpenBankingToolkit/openbanking-reference-implementation/issues/222
https://github.com/OpenBankingToolkit/openbanking-reference-implementation/issues/224
https://github.com/OpenBankingToolkit/openbanking-reference-implementation/issues/223
https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/8
https://github.com/OpenBankingToolkit/openbanking-ui-customization/issues/6
> Incremented versions of dependencies ready for queen-rc7 release

- pom.xml
Bump the aspsp latest release version 1.0.84
aspsp service
> bump the aspsp release version 1.0.84

- pom.xml
Bump the latest version of uk-extension 1.0.10 dependency
> bump the uk-extensions latest version 1.0.10

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/v3_x/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/test/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/test/v3_1_2/CSVFilePaymentConsentsRsApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/test/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/test/v3_1_3/CSVFilePaymentConsentsRsApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_x/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/test/java/com/forgerock/openbanking/extensions/lbg/test/v3_1_2/CSVFilePaymentConsentsRsStoreApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/test/java/com/forgerock/openbanking/extensions/lbg/test/v3_1_3/CSVFilePaymentConsentsRsStoreApiControllerIT.java
- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
Added lbg specific CSVFilePaymentConsentsApi for v3.1.3, including new integration tests.
> Added lbg specific CSVFilePaymentConsentsApi for v3.1.3 (#232)

- forgerock-openbanking-gateway/src/main/java/com/forgerock/openbanking/gateway/GatewayRouteLocatorConfiguration.java
Fix the white list address on scgw.
SCGW
https://github.com/ForgeCloud/ob-deploy/issues/526
> fix for scgw deploy white address list

- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- pom.xml
This PR includes the follows:
- Pulled in v1.0.74 of openbanking-aspsp to include v3.1.3 of the accounts API.
- Added the v3.1.3 endpoints to application.yml.
The required changes to the functional tests are covered here: https://github.com/ForgeCloud/ob-functional-tests/pull/61
> v3.1.3 of the accounts API

- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- pom.xml
Bumped version of openbanking-aspsp to include v3.1.3 and v3.1.4 of the events and funds confirmation APIs. Added the necessary endpoints to application.yml (#216)
> v3.1.3 and v3.1.4 of the events and funds confirmation APIs (#216)

- forgerock-openbanking-config/forgerock-openbanking-git-config/admin/admin.yml
- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
Fixes https://github.com/OpenBankingToolkit/openbanking-reference-implementation/issues/268
> Change spring management config to enable info, health endpoints

- pom.xml
This PR brings in the required changes from openbanking-aspsp in order to populate the debtor name in v3.1.5 responses.
Impacted Areas in Application
* rs-store
> Bumped version of aspsp in order to populate the debtor name in v3.1.5 responses (#272)

- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- pom.xml
Bumped version of aspsp to pull in v3.1.5 of the accounts API and updated `application.yml` for the discovery endpoint (#272)
* rs-api
* rs-store
> Bumped version of aspsp to pull in v3.1.5 of the accounts API

- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- pom.xml
Bumped version of aspsp to pull in v3.1.5 of the events, callback and funds confirmation APIs. Updated application.yml to expose new endpoints (#272)
> Bumped version of aspsp

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- pom.xml
Bumped version of aspsp to pull in v3.1.6 of the Read/Write API. Updated LBG CSV file controllers, plus `application.yml` to expose new endpoints (#272)
* rs-store
* rs-api
> v3.1.6 of the Read/Write APIs.

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
Fixes https://github.com/ForgeCloud/ob-deploy/issues/598
> Create the release version 3.1.6-rem-rc1

- pom.xml
Bumped version of aspsp to pull in fix for account schema name (#258)
* rs-api
> Bumped version of aspsp to pull in fix for account schema name (#258)

- pom.xml
Bumped version of aspsp to pull in fix for idempotency verification (#282)
* rs-api
> Bumped version of aspsp to pull in fix for idempotency verification

- forgerock-openbanking-devportal/forgerock-openbanking-docs/src/main/asciidocs/starterkit/deepdive.adoc
Added details concerning detached JWS headers to the Postman Collection (#263)
> Detached JWS headers documentation

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
> Updated version to 3.1.6-rem-rc2

- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- pom.xml
Added documentation re mongo-migration switch (#279)
Bumped version of aspsp
> Added documentation re mongo-migration switch. Bumped version of aspsp

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
- retag.sh
Set version to 3.1.6-smiths-rc1
> Set project version to smiths-rc1

- pom.xml
- Bumped version [openbanking-aspsp](https://github.com/OpenBankingToolkit/openbanking-aspsp) to [release 1.0.104](https://github.com/OpenBankingToolkit/openbanking-aspsp/releases/tag/1.0.104)
- Bumped version [openbanking-uk-extensions](https://github.com/OpenBankingToolkit/openbanking-uk-extensions) to [release 1.0.17](https://github.com/OpenBankingToolkit/openbanking-uk-extensions/releases/tag/1.0.17)
**[openbanking-aspsp](https://github.com/OpenBankingToolkit/openbanking-aspsp)**
- part fix of [issue 238](https://github.com/OpenBankingToolkit/openbanking-reference-implementation/issues/238)
- Fix and features for **`Callback URL APIs`** for all versions of **`Event Notification API`**
**[openbanking-uk-extensions](https://github.com/OpenBankingToolkit/openbanking-uk-extensions)**
- …
> Bumped versions ASPSP part fix Event Notification API issue 238 and Uk extensions release

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
Bumped version of aspsp and uk-extensions. Using FR model objects in Mongo document classes (#296)
Impacted Areas in Application
* rs-api
* rs-store
> 3.1.6-smiths-rc2 release

- forgerock-openbanking-config/forgerock-openbanking-git-config/aspsp/rs/rs-store/rs-store.yml
- pom.xml
- Set defaults for internal ID filtering
- Incremented version of aspsp for more granular internal ID filtering
* rs-store
> 638: More granular internal ID filtering

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
- Support for Read Refund Account yes/true ([ASPSP](https://github.com/OpenBankingToolkit/openbanking-aspsp))
- Bumped latest version of [ASPSP 1.0.113](https://github.com/OpenBankingToolkit/openbanking-aspsp/releases/tag/1.0.113)
- Bumped latest version of [uk-extensions 1.0.24](https://github.com/OpenBankingToolkit/openbanking-uk-extensions/releases/tag/1.0.24)
- Snapshot version updated to 2.9.10-SNAPSHOT
- [ASPSP](https://github.com/OpenBankingToolkit/openbanking-aspsp)
- [14](https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/14)
- [18](https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/18)
> Snapshot 2.9.10

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/forgerock-openbanking-git-config/application-lbg-example-enables.yml
- forgerock-openbanking-config/forgerock-openbanking-git-config/aspsp/as/as-api/as-api.yml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
- Bumped aspsp version 1.0.114
- Update SNAPSHOT version to 2.9.11-SNAPSHOT
- Bumped common version 1.0.87
Issue: https://github.com/ForgeCloud/ob-deploy/issues/674
> 674: response_types FAPI compliant

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
- Version update to the next release 2.9.11 no snapshot.
> update the version to 2.9.11

- codefresh-publish-release.yml
- Update the pipeline publish release to update the file release-published from ob-deploy root folder.
> Update pipeline publish release

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
Maven release. Use the latest version of aspsp that uses the correct scopes for aggregated polling apis.
issue: https://github.com/OpenBankingToolkit/openbanking-aspsp/issues/327
> 327 aggregated polling api scopes

- .idea/runConfigurations/metrics-service_remote.xml
- README.md
- docker-compose-profiles.yml
- docker-compose.yml
- forgerock-am/Dockerfile
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/v3_0/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_0/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-config/forgerock-openbanking-git-config/metrics/metrics-services.yml
- pom.xml
- Bumped `ob-analytics` version 1.2.0
- Bumped `ob-jwkms` version 1.1.78
- Bumped `ob-auth` version 1.0.67
- Bumped `ob-directory` version 1.4.80
- Bumped `ob-aspsp` version 1.2.0
- Bumped `ob-clients` version 1.1.0
- Bumped `ob-extensions` version 1.2.0
- Bumped `ob-commons` version 1.1.0
- Added `forgerock-openbanking-annotations` dependency
- Refactor controller extensions to use the new origin of annotations.
- Added `analytics-ui` and `analytics-node` to `docker-compose` to complete the platform services.
- Added alternative `docker-compose-profiles` file to use profiles to enhance the possible scenarios and environments in development time.
- Added additional information in readme file about `how use the compose profiles` to run the services in local env.
Issue: …
> 201: Analytics empty data

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/resources/filtered/application.yml
- Delete application.yaml file from rs-store service to enable override the limits values from customer configurations.
Issue:
https://github.com/ForgeCloud/ob-deploy/issues/721
* RS-STORE
> 721: Data api push limits

- docker-compose-profiles.yml
- pom.xml
- Improvement the responses with a clearer message instead of not implemented on `GetAccountStatementFile` [Issue 23](https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/23)
- Fix to upgrade the datatype `countrySubDivision` from List to String. [Issue 27](https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/27)
<details>
<summary>Bumped version table</summary>
| Component |Bumped version|
|---|---|
|[Starter parent](https://github.com/OpenBankingToolkit/openbanking-parent)|[![GitHub release (latest by date)](https://img.shields.io/badge/release-v1.1.88-blue)](https://github.com/OpenBankingToolkit/openbanking-parent/releases/tag/1.1.88)|
|[Analytics](https://github.com/OpenBankingToolkit/openbanking-analytics)|[![GitHub …
> 27: fix datatype countrySubDivision uk-datamodel

- pom.xml
- Bumped aspsp version 1.3.2
- Bumped uk extensions 1.3.1
- Fix self links event-subscriptions
* aspsp
- [Issue 31](https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/31)
> 31: self links served on event-subscriptions

- pom.xml
- Bumped starter parent versio 1.1.97
- Bumped commons 1.1.4
- Bumped clients 1.1.4
- Bumped jwkms 1.1.83
- bumped auth 1.0.71
- Bumped directory 1.4.84
- Bumped analytics 1.2.4
- Bumped aspsp 1.3.4
- Bumped uk extensions 1.3.3
- Improvements in the response when a tpp call the token endpoint.
- Fix bouncycastle transitive dependency conflicts.
- [Feature 742](https://github.com/ForgeCloud/ob-deploy/issues/742)
- [Bouncycastle fix 35](https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/35)
* ASPSP
* JWKMS
> 742:35: token endpoint 500 error and bouncycastle fix

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
* Incremented version to `4.2.0-SNAPSHOT` for the next release containing v3.1.7 of the Read/Write API.
* Bumped version of internal libraries.
* Updated Discovery config for v3.1.7 links to appear.
**Issue**: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/32
* rs-api
* rs-store
> 32: Bumped version of aspsp for v3.1.7 of Read/Write API

- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- pom.xml
Increment version of aspsp for v3.1.8 of the Read/Write API (excluding Variable Recurring Payments (VRPs)).
- rs-api
- rs-store
> 33: v3.1.8 of the Read/Write API, excluding VRPs

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
Create a 4.2.0 release. Contains;
- Read/Write API v3.1.7 https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/32 
- Read/Write API v3.1.8 (without Variable Recurring Payments) https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/33
- Fix to resign id_token keys found in redirect URIs when doing hybrid flow via UI.
- Fix that prevented eIDAS tokens from being accepted when doing DCR as we insisted on OB Test Directory signed certs.
- Better error handling during when using the token endpoint with a different grant_type than supported by the system. Previously client saw a 500 error.
- Correct self links on event subscription responses https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/31
- Consent UI for bulk file payments now works correctly …
> 4.2.0 release branch

- pom.xml
Better error handling and log messages. Refactoring to support changes
to the way we handle registraiton with OBWac certificates.
Issue: https://github.com/OpenBankingToolkit/openbanking-aspsp/pull/440
> 422: Refactored Dynamic Client Registration

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
Better error handling and log messages. Refactoring to support changes
to the way we handle registraiton with OBWac certificates.
Issue: OpenBankingToolkit/openbanking-aspsp#440
> Release 4.2.4

- README.md
> rebase demo

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
When deployed locally the docker image will be built from a named AM war file.
> Release 4.2.5

- docker-compose-profiles.yml
- docker-compose.yml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
- Added Register service to docker compose
- Added manual-onboarding service to docker compose
- Bumped aspsp version 1.4.9
- Bumped uk extensions version 1.4.7
- Upgrade development version to 4.2.8-SNAPSHOT for the next development iteration and release
Transitive Issue: https://github.com/ForgeCloud/ob-deploy/issues/789
> Upgrade versions and features

- forgerock-openbanking-common/src/main/java/com/forgerock/openbanking/common/ApiOBRIExternalCertificates.java
- pom.xml
Issue: https://github.com/ForgeCloud/ob-deploy/issues/775
> 775: Allow TPPs to register mulitple software statements

- .gitignore
- docker-compose.yml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/src/main/java/com/forgerock/openbanking/aspsp/as/ForgerockOpenbankingAsApiApplication.java
- forgerock-openbanking-config/forgerock-openbanking-git-config/application-native.yml
- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- pom.xml
Fixes issues;
https://github.com/ForgeCloud/ob-deploy/issues/796
https://github.com/ForgeCloud/ob-deploy/issues/795
Fixes Bug
Issue: https://github.com/ForgeCloud/ob-deploy/issues/797
All work done as part of issue;
https://github.com/ForgeCloud/ob-deploy/issues/775
> 775: Allow TPPs to register multiple SoftwareStatements with PSD3 eIDAS certs

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
Database upgrade steps for TPP records https://github.com/ForgeCloud/ob-deploy/issues/795
Introduce check to ensure Transport Cert and Software Statement both belong to the same entity. https://github.com/ForgeCloud/ob-deploy/issues/796
Fixes and AM vulnerability
#471 
#470
> Release 4.5.0

- forgerock-openbanking-config/forgerock-openbanking-git-config/application-native.yml
- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- forgerock-openbanking-gateway/src/main/java/com/forgerock/openbanking/gateway/GatewayRouteLocatorConfiguration.java
Also fix and issue with the /api/data/user route that passed a
certificate
Issue: https://github.com/ForgeCloud/ob-deploy/issues/815
> 815: Create customer info route and config settings

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/src/main/java/com/forgerock/openbanking/aspsp/rs/rcs/ForgerockOpenbankingRsApplication.java
- pom.xml
- Bumped aspsp release
- Bumped uk-extensions release
Issue: https://github.com/ForgeCloud/ob-deploy/issues/815
> 815: Implement Customer info

- forgerock-openbanking-config/forgerock-openbanking-git-config/application-native.yml
- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
Fix spring configuration for customer Info endpoints.
> Fix customer info endpoint spring configuration, moved to native profile

- forgerock-openbanking-common/src/main/java/com/forgerock/openbanking/common/CookieHttpSecurityHelper.java
- forgerock-openbanking-common/src/main/java/com/forgerock/openbanking/common/CookieWebSecurityConfiguration.java
- forgerock-openbanking-common/src/main/java/com/forgerock/openbanking/common/DecryptingJwtCookieCollector.java
- forgerock-openbanking-config/forgerock-openbanking-git-config/application-native.yml
- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- forgerock-openbanking-gateway/src/main/java/com/forgerock/openbanking/gateway/GatewayRouteLocatorConfiguration.java
- forgerock-openbanking-gateway/src/main/java/com/forgerock/openbanking/gateway/filters/AddCertificateHeaderGatewayFilter.java
- pom.xml
Added debug to help diagnose what's happening, added config flags for
Customer Info to ensure we get customer info in native (local
deployment), but not by default in our usual deployments.
Issue: https://github.com/ForgeCloud/ob-deploy/issues/831
> 813: Fix /data/user apis

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
RELEASE NOTES
New Features
============
Variable Recurring Payments for v3.1.8
https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/36
Customer Info endpoint - https://github.com/ForgeCloud/ob-deploy/issues/815
Fixes issue
===========
Payment Submission redirection does not meet customer experience
guildelines - https://github.com/ForgeCloud/ob-deploy/issues/794
Ability to create an app Manually is failing
https://github.com/ForgeCloud/ob-deploy/issues/830
User data get's created against TPP, not against PSU user
https://github.com/ForgeCloud/ob-deploy/issues/831
> Release 4.6.0

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
Fix Customer Info data import issue.
Issue: https://github.com/ForgeCloud/ob-deploy/issues/859
> Release 4.6.1

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/test/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/test/v3_1_9/CSVFilePaymentConsentsRsApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/test/java/com/forgerock/openbanking/extensions/lbg/test/v3_1_9/CSVFilePaymentConsentsRsStoreApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
- Updated development version to 4.7.0-SNAPSHOT
- Upgraded CSV file payment extension to support v3.1.9
- Added Integration Test for CSV file payment extension v3.1.9
- Bumped starter parent 2.0.0
- Bumped commons version 1.4.0
- Bumped client version 1.4.0
- Bumped jwkms version 1.4.0
- Bumped auth version 1.4.0
- Bumped directory version 1.7.0
- Bumped analytics version 1.5.0
- Bumped aspsp version 2.0.0
- Bumped uk extensions version 1.8.0
* ASPSP (Read/Write apis v3.1.9)
* CSV File payment
- https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/41
> 41: implementation Read/Write apis v3.1.9

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/test/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/test/v3_1_10/CSVFilePaymentConsentsRsApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/test/java/com/forgerock/openbanking/extensions/lbg/test/v3_1_10/CSVFilePaymentConsentsRsStoreApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
Support Open Banking Read/Write API 3.1.10
- Bump aspsp to 2.1.0
- Bump parent to 2.1.0
- Bump common to 1.5.0
- Bump clients to 1.5.0
- Bump jwkms to 1.5.0
- Bump auth to 1.5.0
https://github.com/ForgeCloud/ob-deploy/issues/872
> Feature/872 ob 3.1.10

- pom.xml
Updating aspsp to 2.1.2
Issue: https://github.com/ForgeCloud/ob-deploy/issues/889
> 889: Updating aspsp to 2.1.2

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
- Support for OB Read/Write API 3.1.10
https://github.com/OpenBankingToolkit/openbanking-reference-implementation/releases/tag/4.8.0
> Release 4.8.0

- pom.xml
Keep all the aspsp versions the same across our 4.8.3 release
Issues:
https://github.com/ForgeCloud/ob-deploy/issues/982 
https://github.com/ForgeCloud/ob-deploy/issues/985
> 992: Fix UI issue and create release using new base images
