OpenBankingToolkit/openbanking-reference-implementation

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-config/forgerock-openbanking-git-config/application-native.yml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
A lot of dependencies are already pulled from the requirements of the
server or core SDK components.
There is also a lot of dependency management coming from the starter
parent pom.
In testing this, I've deleted `~/.m2/repository/` and build, started services ran ob-functional-tests
* None in theory!
Run functional tests
> Remove duplicate dependencies

- .dependabot/config.yml
To reduce burden on the develops we can auto bump and merge. The
concurrency policy has been set to 1 on this CI pipeline to avoid
clashes in the release.json
* versioning
> Auto-merge dependabot

- docker-compose.yml
The output looks like
```
009c76d704e3        openbankingtoolkit/cdr-config                 "sh -c 'java -jar /o  "   About a minute ago   Up About a minute (healthy)            0.0.0.0:8888->8888/tcp                        config
```
* docker-compose
Outline the steps to test or reproduce the PR here.
Run `docker-compose up -d`
Run `docker ps`
Check for healthy
> Add healthcheck to indicate when services are ready

- pom.xml
Use the openbanking-uk-datamodel binaries
- The openbanking reference impementation and dependent code was using
the openbanking-sdk library from the Github ForgeRock organisation. It
should be using the openbanking-uk-datamodel repo from Github
OpenBankingToolkit org.
- This involved updating the latest openbanking-aspsp and parent pom
versions
- See https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/5
> Use the openbanking-uk-datamodel binaries

- forgerock-am/Dockerfile
amster only support the pem format for private keys.
Related with the issue https://github.com/ForgeCloud/ob-reference-implementation/issues/1671
Added the private key conversion to pem format.
AM image.
> Fix the issue related with the private key format

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
Use de integration test support dependency only in test scope to avoid spring conflicts with mocked objects such as WebSecurityConfigAdapter.
Integration Test and Funcional Test.
> Fix test scope integration test support

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/CSVFilePaymentConsentsApiController.java
Fix error with the content type when we validate the supported media type using an extension media types from Spring, for that csv file type case to avoid the content type validation we remove the filter on that csv specific controller.
@see CSVFilePaymentConsentsApiController#csvCreateFilePaymentConsentsConsentIdFile
@see FilePaymentsApiEndpointWrapper#verifyContentTypeHeader
* CSV Files requirement
> Fix the supported media type issue, filter deleted

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/test/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/test/CSVFilePaymentConsentsRsApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/test/java/com/forgerock/openbanking/extensions/lbg/test/CSVFilePaymentConsentsRsStoreApiControllerIT.java
Change the request mapping to set the consume for text/csv media type.
This fix void error the ambiguous handler method mapping when some xml or json consume the submit.
* File payments
> Fix to mapping correctly the consume 

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
Part of https://github.com/OpenBankingToolkit/openbanking-reference-implementation/issues/148
Set to smiths as we have missed REM timescales
> Set mvn version to 3.1.2-smiths-SNAPSHOT

- forgerock-openbanking-directory-services/src/main/java/com/forgerock/openbanking/directory/ForgerockOpenbankingDirectoryApplication.java
> When using a GrantedAuthority directly, such as through the use of an expression like hasAuthority(‘READ_AUTHORITY'), we are restricting the API access in a fine-grained manner.
https://github.com/ForgeCloud/ob-deploy/issues/458
**To set the non-default authority to give access to the user over these protected APIs by specific Authority we need**:
- Collect additional authorities from AM JWT authentication cookie.
- To give user access to restricted APIs protected by authorities in fine-grained manner.
- Avoid give default access to these restricted APIs protected by specific authorities.
* Adding the default authorities.
* Adding the authorities coming from Forgerock AM JWT Cookie authentication if exist authorities.
* FYI: Additional Authorities setted on Claim 'group' set in …
> Non-default authorities from AM JWT authentication cookie

- .idea/runConfigurations/rs_ui_remote.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/src/main/java/com/forgerock/openbanking/rs/ui/ForgerockOpenbankingRsUiApplication.java
**Describe the bug**
Not able to fetch user data of a PSU from forgeRock
https://github.com/ForgeCloud/ob-reference-implementation/issues/1876
**Expected behaviour**
The data related with the user authenticated by user session.
**Release Notes**
Cookie collector implemented in the authorisation adapter sequence.
**Affected App**: RS-UI
Description: X
> Fix issue 1876 - Not able to fetch user data of a PSU from forgeRock

- codefresh.yml
We need to tag the images with the pom version also, and the commit hash to help find the images on the registry, until now the images builded were tagged "latest" only. We need more tags for these images on the registry.
Deployment method.
> Tag images master branch

- codefresh.yml
- or deploys for anything other than latest doesn't work
This is because after deploying to lbg-dev images weren't found. Looking in gcr the last run of the pipeline only tagged images with `latest`
> Tag pushed docker images with ${{PROJECT_VERSION}}-${{CF_SHORT_REVISION}}

- forgerock-openbanking-gateway/src/main/resources/filtered/logback-spring.xml
- pom.xml
Part fix for #196
Some implementors have expressed a need to be able to enfore that a
PaymentCodeContext is provided in the Risk object when requesting a
consent. This PR enables this feature to be turned on by setting the
following spring config setting to true;
rs.api.payment.validate.risk.require-payment-context-code
This change is included in v1.0.83 of openbanking-aspsp
> Make OBRisk1.PaymentContextCode field configurably a required field

- pom.xml
Bumped version of aspsp to fix conversion of OB model objects in versions prior to v3.1.3 (#232). The ob-functional-tests (master branch) runs successfully against this version.
> Bumped version of aspsp to fix conversion of OB model objects

- pom.xml
Bumped the version of:
- starter parent 1.0.73
- aspsp 1.0.86
* ASPSP
This update fix the issue:
https://github.com/ForgeCloud/ob-reference-implementation/issues/1877
> Bumped the parent version 1.0.73 and aspsp 1.0.86

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/v3_0/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/test/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/test/v3_1_4/CSVFilePaymentConsentsRsApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_0/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/test/java/com/forgerock/openbanking/extensions/lbg/test/v3_1_4/CSVFilePaymentConsentsRsStoreApiControllerIT.java
- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- pom.xml
This PR includes the following:
- v1.0.88 of openbanking-aspsp to pull in the latest changes for v3.1.3 of the accounts API and v3.1.4 of the accounts and payment APIs.
- Adds the v3.1.4 endpoints to `application.yml`.
- Updates the lbg specific CSV file controllers.
Following this PR, we need to update these areas of Read/Write API:
- Aggregated Polling
- Callback URLs
- Events Subscription
- Confirmation of funds
* rs-store
* rs-api
> v3.1.3 of the accounts API and v3.1.4 of both the accounts and payments API

- pom.xml
This PR pulls in the latest version of `openbanking-aspsp` which concerns the removal of the b64 claim header in detached JWTs in v3.1.4 of the API. See [waiver 007](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/1112670669/W007) for more details.
> Bumped versions of ob-aspsp and ob-extensions (#262)

- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- pom.xml
- Deleted the key apis:version: "" on [application.yml file](https://github.com/OpenBankingToolkit/openbanking-reference-implementation/blob/master/forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml)
Populate the latest versions of Open Banking libraries:
- [uk extensions](https://github.com/OpenBankingToolkit/openbanking-uk-extensions) 1.0.12
- [starter parent](https://github.com/OpenBankingToolkit/openbanking-parent) 1.0.75
- [aspsp](https://github.com/OpenBankingToolkit/openbanking-aspsp) 1.0.91
- [directory](https://github.com/OpenBankingToolkit/openbanking-directory) 1.4.74
- [analytics](https://github.com/OpenBankingToolkit/openbanking-analytics) 1.1.50
- [auth](https://github.com/OpenBankingToolkit/openbanking-auth) 1.0.59
- …
> bumped the latest version of openbanking libraries and starter parent

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/v3_0/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/test/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/test/v3_1_2/CSVFilePaymentConsentsRsApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/test/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/test/v3_1_5/CSVFilePaymentConsentsRsApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_0/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/test/java/com/forgerock/openbanking/extensions/lbg/test/v3_1_2/CSVFilePaymentConsentsRsStoreApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/test/java/com/forgerock/openbanking/extensions/lbg/test/v3_1_4/CSVFilePaymentConsentsRsStoreApiControllerIT.java
- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- pom.xml
This PR brings in the required changes from `openbanking-aspsp` and `openbanking-uk-datamodel` (via the parent pom) to support v3.1.5 of the Payments API.
It also makes the required changes to support CSV File based payments for LBG and lists the new v3.1.5 endpoints within`forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml` (so that they appear in the Discovery API).
* rs-api
* rs-store
> Required changes to support v3.1.5 of the payments API (#272)

- pom.xml
Bumped version of aspsp to include validation of the b64 claims header in a detached JWS (#280)
Validation has been added to ensure the b64 claims header is present and set to false in a detached JWS, if the version is v.3.1.3 or earlier.
If the version is v3.1.4 or later, the application ensures the b64 claims header is not included.
Additionally, validation has been added to ensure that a null detached JWS cannot be provided if the verification of detached signatures is enabled in the config. 
* rs-api
> Bumped version of aspsp to include validation of the b64 claims header (#280)

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ForgerockOpenbankingRsStoreApplication.java
- pom.xml
Added Mongobee for migration of mongo data. Bumped version of aspsp to migrate OB objects from v3.1.2 to v3.1.6 (#279)
Mongobee is essentially a Mongo equivalent of liquibase. It runs when the application starts up and checks to see if any new ChangeLogs need to be applied.
* rs-store
> Migration of mongo data from v3.1.2 to v3.1.6 (#279)

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/v3_0/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/test/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/test/v3_1_2/CSVFilePaymentConsentsRsApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/test/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/test/v3_1_5/CSVFilePaymentConsentsRsApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_0/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsRsStoreApiController.java
- pom.xml
**Enhance**:
- ContentType defined to consume the CSV File payment api changed to `text/plain` instead of `text/csv`
Resolves https://github.com/ForgeCloud/ob-deploy/issues/606
The customer want consume the CSVFilePayment API using the MIME type text/plain instead of text/csv that was the Mime type defined in the specification:
https://docs.google.com/document/d/1rbwLWf7pNh4_h9i2qPgy1BhQ5xUECUpQwY63OOJjqf0/edit#
Reference implementation [aspsp]
- rs-api
- rs-store
> CSV File Payment Enhancement

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ForgerockOpenbankingRsStoreApplication.java
Migration of FR document classes disabled by default ('rs.mongo-migration.enabled' must be set to true).
> Added switch to enable/disable rs-store data migration

- pom.xml
- Bumped version [openbanking-aspsp](https://github.com/OpenBankingToolkit/openbanking-aspsp) to [release 1.0.105](https://github.com/OpenBankingToolkit/openbanking-aspsp/releases/tag/1.0.105)
- Fix the issue 238 - Event Notifications
- Bumped version [openbanking-uk-extensions](https://github.com/OpenBankingToolkit/openbanking-uk-extensions) to [release 1.0.18](https://github.com/OpenBankingToolkit/openbanking-uk-extensions/releases/tag/1.0.18)
**[openbanking-aspsp](https://github.com/OpenBankingToolkit/openbanking-aspsp)**
- part fix of [issue 238](https://github.com/OpenBankingToolkit/openbanking-reference-implementation/issues/238)
- Fix and features for **`Event subscription API`** and **`Aggregated polling API`** for all versions (3.1.2 to 3.1.6) of **`Event Notification API`** …
> Update ob depedencies

- pom.xml
**Change log**
- Bumped latest [openbanking-aspsp](https://github.com/OpenBankingToolkit/openbanking-aspsp) release [version 1.0.106](https://github.com/OpenBankingToolkit/openbanking-aspsp/releases/tag/1.0.106)
- Fix Event Notification APIs for all versions (3.0 to 3.1.6)
- Bumped latest [openbanking-uk-extensions](https://github.com/OpenBankingToolkit/openbanking-uk-extensions) release [version 1.0.19](https://github.com/OpenBankingToolkit/openbanking-uk-extensions/releases/tag/1.0.19)
- Fix part of [Issue 238](https://github.com/OpenBankingToolkit/openbanking-reference-implementation/issues/238)
Bumped release versions OB libraries.
* ASPSP
* UK Extensions
> Feature 238 - Event Notifications API

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ForgerockOpenbankingRsStoreApplication.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_0/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/test/java/com/forgerock/openbanking/extensions/lbg/test/MockTppHelper.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/test/java/com/forgerock/openbanking/extensions/lbg/test/v3_1_2/CSVFilePaymentConsentsRsStoreApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/test/java/com/forgerock/openbanking/extensions/lbg/test/v3_1_4/CSVFilePaymentConsentsRsStoreApiControllerIT.java
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- pom.xml
According to the OB spec, when at TPP signs messages with an OB cert,
the iss field of the jws header should be set to
{{orgId}}/{{softwareId}} where the orgId is the OpenBanking organisation
with which the certificates used belong to, and sofware Id indicates the
Software Statement or software client Id of the Open Banking registered
TPP.
See issue https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/12
> Expect TPPs jws sigs to have correct issuer field

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/v3_0/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/main/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/test/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/test/v3_1_2/CSVFilePaymentConsentsRsApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/src/test/java/com/forgerock/openbanking/aspsp/rs/ext/lbg/file/payment/csv/test/v3_1_5/CSVFilePaymentConsentsRsApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_0/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/test/java/com/forgerock/openbanking/extensions/lbg/test/v3_1_2/CSVFilePaymentConsentsRsStoreApiControllerIT.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/test/java/com/forgerock/openbanking/extensions/lbg/test/v3_1_4/CSVFilePaymentConsentsRsStoreApiControllerIT.java
- pom.xml
Bumped version of aspsp and uk-extensions. Using FR model objects in Mongo document classes (#296)
The change in aspsp is significant and introduces the following changes:
* Removed all unused FR payment consent and submission mongo "documents" and repositories.
* Moved the remaining FR documents and repositories into one folder.
* Removed the number suffix from the FR documents and repositories (e.g. we now just have FRDomesticConsent).
* Deprecated the legacy FR documents which we've had to retain for migration purposes (they've been placed in a legacy package).
* Fixed idempotent checks in controllers and made logging more consistent.
This means that when a new version of the Payments API introduces new OB model objects, we do not need to add new mongo "documents" and corresponding …
> Bumped version of aspsp and uk-extensions. Using FR model objects in Mongo document classes (#296)

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
- Support onboarding with an OBWac and OBSeal certificate.
- Payment `Refund` fixes [14](https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/14)
- Bumped latest starter parent [version 1.0.86](https://github.com/OpenBankingToolkit/openbanking-parent/releases/tag/1.0.86)
- Bumped latest uk extensions [version 1.0.23](https://github.com/OpenBankingToolkit/openbanking-uk-extensions/releases/tag/1.0.23)
* as-rs
* as-api
- [Issue 635](https://github.com/ForgeCloud/ob-deploy/issues/635)
- [Issue 14](https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/14) ([16](https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/16))
> 635 support obwac and obseal as transport and signing certs for tpps

- codefresh-publish-release.yml
Fix misleading commit message
Issue: https://github.com/ForgeCloud/ob-deploy/issues/680
> 680: Fix commit comment for updates to release-published.json

- forgerock-am/amster/config/realms/root-openbanking/OAuth2Provider.json
- forgerock-openbanking-devportal/forgerock-openbanking-docs/src/main/asciidocs/starterkit/quickstart.adoc
- Added supported scope `eventpolling` to **AM local config** `Oauth provider service`.
- [Issue 327](https://github.com/OpenBankingToolkit/openbanking-aspsp/issues/327)
> 327: Aggregated polling scopes

- forgerock-openbanking-config/forgerock-openbanking-git-config/application-native.yml
- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
For this next round of deployment we will have the default API version set to 3.1.6
Issue: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/19
> 19: Default read/write api version is 3.1.6

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_0/CSVFilePaymentConsentsRsStoreApiController.java
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/src/main/java/com/forgerock/openbanking/aspsp/rs/store/ext/lbg/file/payment/csv/api/v3_1_3/CSVFilePaymentConsentsRsStoreApiController.java
- pom.xml
- Bumped apsps version 1.3.1
- Bumped uk extensions version 1.3.0
- Bumped jacoco maven plugin version 0.8.7
- Fix payments metadata for csv file payments
* csv file payment (uk extension)
* aspsp
- [Issue 30](https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/30)
> 30: cvs file payment details

- README.md
- docker-compose-profiles.yml
- docker-compose.yml
Make able the customer, with no access to set protected credentials, run the services with docker-compose 
- Added simulated default value for GCP credentials to run the services
- [Feature 410](https://github.com/OpenBankingToolkit/openbanking-reference-implementation/issues/410)
* docker-compose
* RS-STORE
> 410: simulated default value for CGP Credentials

- pom.xml
- Bumped [Aspsp](https://github.com/OpenBankingToolkit/openbanking-aspsp) version [1.4.1](https://github.com/OpenBankingToolkit/openbanking-aspsp/releases/tag/1.4.1)
- Bumped [uk-extensions](https://github.com/OpenBankingToolkit/openbanking-uk-extensions) version [1.4.1](https://github.com/OpenBankingToolkit/openbanking-uk-extensions/releases/tag/1.4.1)
- Removed accidental import of bouncycastle postalAddress (aspsp)
- [Feature 405: bouncycastle postalAddress removed](https://github.com/OpenBankingToolkit/openbanking-aspsp/pull/405)
* ASPSP
> Bumped versions

- forgerock-am/amster/amster-install.sh
Issue: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/37
Fixes an issue when building AM image for the first time. I was seeing
an issue when the Docker image was being built and amster was trying to
call AM to check to see if it had started, but of course couldn't reach
it. This fixes that issue.
> 37: Add AM entry to /etc/hosts

- forgerock-openbanking-common/src/main/java/com/forgerock/openbanking/common/ApiOBRIExternalCertificates.java
But allow psd2 certs to be signed by any trusted entity.
Issue: https://github.com/ForgeCloud/ob-deploy/issues/740
> 740: Restrict non-eIDAS certs to OB or OBRI signed certs

- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
- pom.xml
The id_token in the hybrid flow redirect url was not verifyable. We need
to resign the token issued by AM so that we can put the correct key id
(kid) into the jwt - the kid needs to match that of the kid in the OB
jwks_uri in order for it to be verifiable. AM assignes UUID keyIds
rather than the SHA1 hash of the certificate as specified by the OB
directory. See OPENAM-10425.
> 745: sandbox id token key verification fails

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
749: provide default value for authorize x-headless-auth-enabled param Include new versions of aspsp and uk-extensions that include a fix for;
Issue: ForgeCloud/ob-deploy#749
Also includes release commit for 4.2.1
> 749 provide default value for authorize x headless auth enabled param rebased and release 4.2.1

- forgerock-openbanking-common/src/main/java/com/forgerock/openbanking/common/ApiOBRIExternalCertificates.java
- forgerock-openbanking-common/src/main/java/com/forgerock/openbanking/common/OBRICertificateConfiguration.java
- forgerock-openbanking-common/src/main/java/com/forgerock/openbanking/common/OBRIExternalCertificates.java
Remove the unregistered TPP role and change the getUsername method to return the `authorisationNumber` which is the `organisationId` in the psd2certinfo class.
issue: https://github.com/ForgeCloud/ob-deploy/issues/775
> allow for multiple registeration

- docker-compose-profiles.yml
- docker-compose.yml
- forgerock-am/README.md
- Added new OpenAM war version that fix the below security issue:
- Removed vulnerable endpoints
- Reference: https://wikis.forgerock.org/confluence/pages/viewpage.action?spaceKey=SA&title=15+Sept+2021+-+AM+Session+Vulnerability
Issue: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/40
- In all versions of AM there is a session hijacking vulnerability that allows anyone to take control of an active session in AM. This means any AM admin console or user session can be spoofed.
* AM (local environment)
> 40: AM session vulnerability

- pom.xml
While the VRP controllers are not yet in place, the following issue alluded to problems with the swagger generation;
https://github.com/OpenBankingToolkit/openbanking-aspsp/pull/421
A newer version (3.1.8r5) of the swagger files are available and I have regenerated the datamodels, and the VRP controllers from this swagger spec. 
This PR only adds the new model changes to the openbanking-uk-datamodel and changes all components to use the new models. ASPSP required some changes to convert the new Funds Conformation classes to FR classes for storage. 
Issue: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/36
> 36: Now uses latest 3.1.8r5 datamodels for VRP and Funds Conf

- pom.xml
Now adds username as a field to CustomerInfo before persisting.
This means that the RCS will be able to find by username.
Issue: https://github.com/ForgeCloud/ob-deploy/issues/859
> 859: Imports customer info correctly

- .gitignore
- docker-compose-profiles.yml
- docker-compose.yml
- forgerock-am/Dockerfile
- forgerock-am/README.md
- forgerock-am/amster/config/global/Platform.json
- Prepare for the next advisory patch
- Upgraded OB OpenAM from version 6.5.1 to version 6.5.5
Issue: https://github.com/forgecloud/ob-deploy/issues/925
> 925: OB AM version patched upgrade

- docker-compose-profiles.yml
- docker-compose.yml
- forgerock-am/Dockerfile
- forgerock-am/README.md
- forgerock-am/amster/config/global/Platform.json
**Patch security advisor 202204**
- https://backstage.forgerock.com/knowledge/kb/article/a90639318
- Upgraded to use the new openam 6.5.1 patched with 202204 security advisor  
Issue: https://github.com/ForgeCloud/ob-deploy/issues/925
Relevant comment: https://github.com/ForgeCloud/ob-deploy/issues/925#issuecomment-1310519670
> 925: AM 6.5.1 security patch 202204

- forgerock-openbanking-config/forgerock-openbanking-git-config/aspsp/as/as-api/as-api.yml
Some offered methods were not FAPI compliant
Issue: https://github.com/forgecloud/ob-deploy/issues/943
> 943: Remove non fapi compliant token-endpoint-auth-methods

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
Use latest v1.5.2 of the commons library and versions of library that also use that version. This fixes an issue with the TLA country code mapping that is use to reconstruct transport key's Organization Identifier from Open Banking Software Statements.
Issue: https://github.com/ForgeCloud/ob-deploy/issues/949
> 949 fix three letter country code mapping for latvia

- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/forgerock-openbanking-as-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-as/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-api/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-rcs/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-simulator/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-store/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/forgerock-openbanking-rs-ui/pom.xml
- forgerock-openbanking-aspsp/forgerock-openbanking-aspsp-rs/pom.xml
- forgerock-openbanking-aspsp/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-admin/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/forgerock-openbanking-metrics-services/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-metrics/pom.xml
- forgerock-openbanking-backstage/forgerock-openbanking-monitoring/pom.xml
- forgerock-openbanking-backstage/pom.xml
- forgerock-openbanking-common/pom.xml
- forgerock-openbanking-config/Dockerfile
- forgerock-openbanking-config/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-docs/pom.xml
- forgerock-openbanking-devportal/forgerock-openbanking-register/pom.xml
- forgerock-openbanking-devportal/pom.xml
- forgerock-openbanking-directory-services/pom.xml
- forgerock-openbanking-gateway/pom.xml
- forgerock-openbanking-jwkms/pom.xml
- pom.xml
Open Banking SSAs have software_version as a string rather than a double
Issue: https://github.com/forgecloud/ob-deploy/issues/965
> 965 accept new ob directory ssa format - and release 4.8.2

- forgerock-openbanking-config/forgerock-openbanking-git-config/application.yml
Functional tests against all versions takes forever.
Issue: https://github.com/ForgeCloud/ob-deploy/issues/996
> 996: Support only ob v3.1.10 onward in master
